Carregando Libs

In [13]:
import pandas as pd
import copy

Carregando conexões

In [29]:
base = pd.read_csv(r'C:\Users\felipe.ferraz\OneDrive - Yandeh\Área de Trabalho\00 - COISAS ÚTEIS\10 - MODELAGEM\01 - CASA DO ADUBO\hp_all.csv')
# Tratando CNPJ
base['DOCUMENTO'] = base['DOCUMENTO'].astype(str)
base['DOCUMENTO'] = base['DOCUMENTO'].str.replace(r'\.0$', '', regex=True)
base['DOCUMENTO'] = base['DOCUMENTO'].astype(str)
base['QTD_CARACTERES'] = base['DOCUMENTO'].str.len()
base['DOCUMENTO'] = base['DOCUMENTO'].astype(str).str.zfill(14)
base['DOCUMENTO'] = base['DOCUMENTO'].str.replace(r'\s+', '', regex=True)
# Filtrando CNPJ's Invalidos
base = base[base['QTD_CARACTERES'] >= 6]

base = base.drop_duplicates()
base

C:\Users\felipe.ferraz\AppData\Local\Temp\ipykernel_12584\4204778216.py:1: DtypeWarning: Columns (3,10) have mixed types. Specify dtype option on import or set low_memory=False.
  base = pd.read_csv(r'C:\Users\felipe.ferraz\OneDrive - Yandeh\Área de Trabalho\00 - COISAS ÚTEIS\10 - MODELAGEM\01 - CASA DO ADUBO\hp_all.csv')

,DOCUMENTO,RAZAO_SOCIAL,NUMERO_TITULO,NUMERO_PARCELA,DT_FATURAMENTO,DT_VENCIMENTO,DT_PAGAMENTO,VALOR_TITULO,DT_HP,FORNECEDOR,REGIAO,QTD_CARACTERES
0,00074887300204,ADELINO BIAZAO JUNIOR,1-18-57628,1.0,2023-02-27,2023-03-04,NaN,1150.00,2023-02-27,Casa do Adubo,NaN,11
1,00052429245949,ADEMAR FRANCISCO HEMSING,1-5-97584,1.0,2022-09-14,2023-04-30,NaN,295000.00,2023-02-27,Casa do Adubo,NaN,11
2,00089267427172,ADILSON RODRIGUES DE SOUZA,1-5-99395,1.0,2023-01-31,2023-03-07,NaN,890.00,2023-02-27,Casa do Adubo,NaN,11
3,00087589753653,ADRIANO SOARES BARBOSA,1-31-5450,1.0,2022-05-02,2023-04-16,NaN,1099.35,2023-02-27,Casa do Adubo,NaN,11
4,00087589753653,ADRIANO SOARES BARBOSA,1-31-5472,1.0,2022-05-03,2023-04-17,NaN,1099.35,2023-02-27,Casa do Adubo,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...
1426800,32149587000191,ZEDEQUIAS GONCALVES DE ANDRADE 32253773840,53993701,NaN,2023-05-10,2023-05-17,2023-05-19,239.80,2023-05-19,Multypet,NaN,14
1426801,32149587000191,ZEDEQUIAS GONCALVES DE ANDRADE 32253773840,53780001,NaN,2023-03-08,2023-03-15,2023-03-16,479.95,2023-05-19,Multypet,NaN,14
1426802,32149587000191,ZEDEQUIAS GONCALVES DE ANDRADE 32253773840,53761501,NaN,2023-03-01,2023-03-08,2023-03-10,815.50,2023-05-19,Multypet,NaN,14
1426803,32149587000191,ZEDEQUIAS GONCALVES DE ANDRADE 32253773840,53876002,NaN,2023-04-04,2023-04-18,2023-05-05,302.80,2023-05-19,Multypet,NaN,14
1426804,32149587000191,ZEDEQUIAS GONCALVES DE ANDRADE 32253773840,54017601,NaN,2023-05-17,2023-05-24,NaN,316.40,2023-05-19,Multypet,NaN,14

## Começando Tratamento dos dados

# Quantidade de títulos em aberto (vencido);

In [30]:
qtde_titulos_abertos_vencidos = copy.copy(base)
#Pegando somente casos válidos para análise
qtde_titulos_abertos_vencidos = qtde_titulos_abertos_vencidos[qtde_titulos_abertos_vencidos['DT_VENCIMENTO'] < qtde_titulos_abertos_vencidos['DT_HP']]
qtde_titulos_abertos_vencidos = qtde_titulos_abertos_vencidos[pd.isna(qtde_titulos_abertos_vencidos['DT_PAGAMENTO'])]
qtde_titulos_abertos_vencidos = qtde_titulos_abertos_vencidos.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'NUMERO_TITULO': 'count'
}).reset_index()
qtde_titulos_abertos_vencidos.columns = ['DOCUMENTO', 'FORNECEDOR', 'QTDE_TITULOS_ABERTOS_VENCIDOS']

qtde_titulos_abertos_vencidos

           DOCUMENTO     FORNECEDOR  QTDE_TITULOS_ABERTOS_VENCIDOS
0     00000003614298  Casa do Adubo                              3
1     00000009751254  Casa do Adubo                              1
2     00000009941622  Casa do Adubo                              1
3     00000030005248  Casa do Adubo                              1
4     00000033471924  Casa do Adubo                             15
...              ...            ...                            ...
3787  73418758000118  Casa do Adubo                             10
3788  83773390000160  Casa do Adubo                              1
3789  84046101026400  Casa do Adubo                              1
3790  94077518000924  Casa do Adubo                              1
3791  97552416000154  Casa do Adubo                              6

[3792 rows x 3 columns]

# Valor total títulos em aberto(vencido);

In [31]:
valor_titulos_abertos_vencidos = copy.copy(base)
#Pegando somente casos válidos para análise
valor_titulos_abertos_vencidos = valor_titulos_abertos_vencidos[valor_titulos_abertos_vencidos['DT_VENCIMENTO'] < valor_titulos_abertos_vencidos['DT_HP']]
valor_titulos_abertos_vencidos = valor_titulos_abertos_vencidos[pd.isna(valor_titulos_abertos_vencidos['DT_PAGAMENTO'])]
valor_titulos_abertos_vencidos = valor_titulos_abertos_vencidos.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'VALOR_TITULO': 'sum'
}).reset_index()
valor_titulos_abertos_vencidos.columns = ['DOCUMENTO', 'FORNECEDOR', 'VALOR_TITULOS_ABERTOS_VENCIDOS']

valor_titulos_abertos_vencidos

           DOCUMENTO     FORNECEDOR  VALOR_TITULOS_ABERTOS_VENCIDOS
0     00000003614298  Casa do Adubo                        40025.00
1     00000009751254  Casa do Adubo                         1179.00
2     00000009941622  Casa do Adubo                         1140.00
3     00000030005248  Casa do Adubo                         9010.00
4     00000033471924  Casa do Adubo                      2366901.75
...              ...            ...                             ...
3787  73418758000118  Casa do Adubo                         5249.33
3788  83773390000160  Casa do Adubo                        24003.00
3789  84046101026400  Casa do Adubo                       225000.00
3790  94077518000924  Casa do Adubo                         3648.00
3791  97552416000154  Casa do Adubo                        16313.59

[3792 rows x 3 columns]

# Quantidade de títulos em aberto (vincendo);

In [32]:
qtde_titulos_abertos_vincendo = copy.copy(base)
#Pegando somente casos válidos para análise
qtde_titulos_abertos_vincendo = qtde_titulos_abertos_vincendo[qtde_titulos_abertos_vincendo['DT_VENCIMENTO'] > qtde_titulos_abertos_vincendo['DT_HP']]
qtde_titulos_abertos_vincendo = qtde_titulos_abertos_vincendo[pd.isna(qtde_titulos_abertos_vincendo['DT_PAGAMENTO'])]
qtde_titulos_abertos_vincendo = qtde_titulos_abertos_vincendo.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'NUMERO_TITULO': 'count'
}).reset_index()
qtde_titulos_abertos_vincendo.columns = ['DOCUMENTO', 'FORNECEDOR', 'QTDE_TITULOS_ABERTOS_VINCENDO']

qtde_titulos_abertos_vincendo

            DOCUMENTO     FORNECEDOR  QTDE_TITULOS_ABERTOS_VINCENDO
0      00000003602524  Casa do Adubo                              1
1      00000003992640  Casa do Adubo                              6
2      00000009643605  Casa do Adubo                              5
3      00000010350292  Casa do Adubo                              1
4      00000011479191  Casa do Adubo                             18
...               ...            ...                            ...
16329  97462022000105  Casa do Adubo                              2
16330  97533978000150  Casa do Adubo                              2
16331  97542837000102  Casa do Adubo                              9
16332  97552416000154  Casa do Adubo                              3
16333  97837181001976  Casa do Adubo                              1

[16334 rows x 3 columns]

# Valor total de títulos em aberto (vincendo);

In [33]:
valor_titulos_abertos_vincendo = copy.copy(base)
#Pegando somente casos válidos para análise
valor_titulos_abertos_vincendo = valor_titulos_abertos_vincendo[valor_titulos_abertos_vincendo['DT_VENCIMENTO'] > valor_titulos_abertos_vincendo['DT_HP']]
valor_titulos_abertos_vincendo = valor_titulos_abertos_vincendo[pd.isna(valor_titulos_abertos_vincendo['DT_PAGAMENTO'])]
valor_titulos_abertos_vincendo = valor_titulos_abertos_vincendo.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'VALOR_TITULO': 'sum'
}).reset_index()
valor_titulos_abertos_vincendo.columns = ['DOCUMENTO', 'FORNECEDOR', 'VALOR_TITULOS_ABERTOS_VINCENDO']

valor_titulos_abertos_vincendo

            DOCUMENTO     FORNECEDOR  VALOR_TITULOS_ABERTOS_VINCENDO
0      00000003602524  Casa do Adubo                         7400.00
1      00000003992640  Casa do Adubo                        70382.02
2      00000009643605  Casa do Adubo                        16010.82
3      00000010350292  Casa do Adubo                         5500.00
4      00000011479191  Casa do Adubo                        16487.00
...               ...            ...                             ...
16329  97462022000105  Casa do Adubo                         3410.20
16330  97533978000150  Casa do Adubo                         3860.00
16331  97542837000102  Casa do Adubo                         7288.20
16332  97552416000154  Casa do Adubo                        13739.93
16333  97837181001976  Casa do Adubo                         3062.50

[16334 rows x 3 columns]

# Prazo Médio das operações em aberto(vencido);

In [34]:
prazo_medio_abertos_vencidos = copy.copy(base)
#Pegando somente casos válidos para análise
prazo_medio_abertos_vencidos = prazo_medio_abertos_vencidos[prazo_medio_abertos_vencidos['DT_VENCIMENTO'] < prazo_medio_abertos_vencidos['DT_HP']]
prazo_medio_abertos_vencidos = prazo_medio_abertos_vencidos[pd.isna(prazo_medio_abertos_vencidos['DT_PAGAMENTO'])]
# Criando aux para cálculo prazo médio
prazo_medio_abertos_vencidos['DT_VENCIMENTO'] = pd.to_datetime(prazo_medio_abertos_vencidos['DT_VENCIMENTO'])
prazo_medio_abertos_vencidos['DT_FATURAMENTO'] = pd.to_datetime(prazo_medio_abertos_vencidos['DT_FATURAMENTO'])

prazo_medio_abertos_vencidos['AUX_PRAZO_MEDIO'] = (prazo_medio_abertos_vencidos['DT_VENCIMENTO'] - prazo_medio_abertos_vencidos['DT_FATURAMENTO']).dt.days
prazo_medio_abertos_vencidos = prazo_medio_abertos_vencidos.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'AUX_PRAZO_MEDIO': 'mean'
}).reset_index()
prazo_medio_abertos_vencidos.columns = ['DOCUMENTO', 'FORNECEDOR', 'PRAZO_MEDIO_ABERTOS_VENCIDOS']

prazo_medio_abertos_vencidos

           DOCUMENTO     FORNECEDOR  PRAZO_MEDIO_ABERTOS_VENCIDOS
0     00000003614298  Casa do Adubo                    136.666667
1     00000009751254  Casa do Adubo                     90.000000
2     00000009941622  Casa do Adubo                     45.000000
3     00000030005248  Casa do Adubo                    210.000000
4     00000033471924  Casa do Adubo                    180.200000
...              ...            ...                           ...
3787  73418758000118  Casa do Adubo                    107.200000
3788  83773390000160  Casa do Adubo                     60.000000
3789  84046101026400  Casa do Adubo                     25.000000
3790  94077518000924  Casa do Adubo                     34.000000
3791  97552416000154  Casa do Adubo                    165.000000

[3792 rows x 3 columns]

# Prazo Médio das operações em aberto(vincendo);

In [35]:
prazo_medio_abertos_vincendos = copy.copy(base)
#Pegando somente casos válidos para análise
prazo_medio_abertos_vincendos = prazo_medio_abertos_vincendos[prazo_medio_abertos_vincendos['DT_VENCIMENTO'] > prazo_medio_abertos_vincendos['DT_HP']]
prazo_medio_abertos_vincendos = prazo_medio_abertos_vincendos[pd.isna(prazo_medio_abertos_vincendos['DT_PAGAMENTO'])]
# Criando aux para cálculo prazo médio
prazo_medio_abertos_vincendos['DT_VENCIMENTO'] = pd.to_datetime(prazo_medio_abertos_vincendos['DT_VENCIMENTO'])
prazo_medio_abertos_vincendos['DT_FATURAMENTO'] = pd.to_datetime(prazo_medio_abertos_vincendos['DT_FATURAMENTO'])

prazo_medio_abertos_vincendos['AUX_PRAZO_MEDIO'] = (prazo_medio_abertos_vincendos['DT_VENCIMENTO'] - prazo_medio_abertos_vincendos['DT_FATURAMENTO']).dt.days
prazo_medio_abertos_vincendos = prazo_medio_abertos_vincendos.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'AUX_PRAZO_MEDIO': 'mean'
}).reset_index()
prazo_medio_abertos_vincendos.columns = ['DOCUMENTO', 'FORNECEDOR', 'PRAZO_MEDIO_ABERTOS_VINCENDOS']

prazo_medio_abertos_vincendos

            DOCUMENTO     FORNECEDOR  PRAZO_MEDIO_ABERTOS_VINCENDOS
0      00000003602524  Casa do Adubo                     165.000000
1      00000003992640  Casa do Adubo                     315.333333
2      00000009643605  Casa do Adubo                     287.000000
3      00000010350292  Casa do Adubo                     150.000000
4      00000011479191  Casa do Adubo                     143.333333
...               ...            ...                            ...
16329  97462022000105  Casa do Adubo                     135.000000
16330  97533978000150  Casa do Adubo                      45.000000
16331  97542837000102  Casa do Adubo                     180.000000
16332  97552416000154  Casa do Adubo                     150.000000
16333  97837181001976  Casa do Adubo                     170.000000

[16334 rows x 3 columns]

# Quantidade de títulos liquidados;

In [36]:
qtde_titulos_liquidados = copy.copy(base)
#Pegando somente casos válidos para análise
qtde_titulos_liquidados = qtde_titulos_liquidados[pd.notna(qtde_titulos_liquidados['DT_PAGAMENTO'])]
qtde_titulos_liquidados = qtde_titulos_liquidados.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'NUMERO_TITULO': 'count'
}).reset_index()
qtde_titulos_liquidados.columns = ['DOCUMENTO', 'FORNECEDOR', 'QTDE_TITULOS_LIQUIDADOS']

qtde_titulos_liquidados

            DOCUMENTO     FORNECEDOR  QTDE_TITULOS_LIQUIDADOS
0      00000000910228  Casa do Adubo                       10
1      00000001339907  Casa do Adubo                        3
2      00000001425650  Casa do Adubo                        2
3      00000001606280  Casa do Adubo                        4
4      00000001607251  Casa do Adubo                        1
...               ...            ...                      ...
94991  97548211000103           Gama                        5
94992  97550450000190           Gama                       16
94993  97550658000109  Casa do Adubo                        6
94994  97551402000116  Casa do Adubo                       11
94995  97552416000154  Casa do Adubo                      108

[94996 rows x 3 columns]

# Valor de títulos liquidados;

In [37]:
valor_titulos_liquidados = copy.copy(base)
#Pegando somente casos válidos para análise
valor_titulos_liquidados = valor_titulos_liquidados[pd.notna(valor_titulos_liquidados['DT_PAGAMENTO'])]
valor_titulos_liquidados = valor_titulos_liquidados.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'VALOR_TITULO': 'sum'
}).reset_index()
valor_titulos_liquidados.columns = ['DOCUMENTO', 'FORNECEDOR', 'VALOR_TITULOS_LIQUIDADOS']

valor_titulos_liquidados

            DOCUMENTO     FORNECEDOR  VALOR_TITULOS_LIQUIDADOS
0      00000000910228  Casa do Adubo                     40.50
1      00000001339907  Casa do Adubo                 168639.74
2      00000001425650  Casa do Adubo                   5214.84
3      00000001606280  Casa do Adubo                   1700.00
4      00000001607251  Casa do Adubo                    291.00
...               ...            ...                       ...
94991  97548211000103           Gama                   4025.04
94992  97550450000190           Gama                  11401.33
94993  97550658000109  Casa do Adubo                   8874.92
94994  97551402000116  Casa do Adubo                   1224.06
94995  97552416000154  Casa do Adubo                 298854.56

[94996 rows x 3 columns]

# Prazo Médio dos títulos liquidados;

In [38]:
prazo_medio_titulos_liquidados = copy.copy(base)
#Pegando somente casos válidos para análise
prazo_medio_titulos_liquidados = prazo_medio_titulos_liquidados[pd.notna(prazo_medio_titulos_liquidados['DT_PAGAMENTO'])]
# Criando aux para cálculo prazo médio
prazo_medio_titulos_liquidados['DT_VENCIMENTO'] = pd.to_datetime(prazo_medio_titulos_liquidados['DT_VENCIMENTO'])
prazo_medio_titulos_liquidados['DT_FATURAMENTO'] = pd.to_datetime(prazo_medio_titulos_liquidados['DT_FATURAMENTO'])

prazo_medio_titulos_liquidados['AUX_PRAZO_MEDIO'] = (prazo_medio_titulos_liquidados['DT_VENCIMENTO'] - prazo_medio_titulos_liquidados['DT_FATURAMENTO']).dt.days
prazo_medio_titulos_liquidados = prazo_medio_titulos_liquidados.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'AUX_PRAZO_MEDIO': 'mean'
}).reset_index()
prazo_medio_titulos_liquidados.columns = ['DOCUMENTO', 'FORNECEDOR', 'PRAZO_MEDIO_TITULOS_LIQUIDADOS']

prazo_medio_titulos_liquidados

            DOCUMENTO     FORNECEDOR  PRAZO_MEDIO_TITULOS_LIQUIDADOS
0      00000000910228  Casa do Adubo                      165.000000
1      00000001339907  Casa do Adubo                       98.000000
2      00000001425650  Casa do Adubo                        0.000000
3      00000001606280  Casa do Adubo                       75.000000
4      00000001607251  Casa do Adubo                       30.000000
...               ...            ...                             ...
94991  97548211000103           Gama                       49.000000
94992  97550450000190           Gama                       50.312500
94993  97550658000109  Casa do Adubo                       50.000000
94994  97551402000116  Casa do Adubo                       43.636364
94995  97552416000154  Casa do Adubo                       69.722222

[94996 rows x 3 columns]

# Atraso Médio liquidados;

In [46]:
atraso_medio_titulos_liquidados = copy.copy(base)
#Pegando somente casos válidos para análise
atraso_medio_titulos_liquidados = atraso_medio_titulos_liquidados[pd.notna(atraso_medio_titulos_liquidados['DT_PAGAMENTO'])]
# Criando aux para cálculo prazo médio
atraso_medio_titulos_liquidados['DT_VENCIMENTO'] = pd.to_datetime(atraso_medio_titulos_liquidados['DT_VENCIMENTO'])
atraso_medio_titulos_liquidados['DT_PAGAMENTO'] = pd.to_datetime(atraso_medio_titulos_liquidados['DT_PAGAMENTO'])

# Calculo Diferenças Dias (Pagamento - Vencimento)
atraso_medio_titulos_liquidados['DIF_DIAS_PAGAMENTO'] = (atraso_medio_titulos_liquidados['DT_PAGAMENTO'] - atraso_medio_titulos_liquidados['DT_VENCIMENTO']).dt.days

atraso_medio_titulos_liquidados = atraso_medio_titulos_liquidados.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'DIF_DIAS_PAGAMENTO': 'mean'
}).reset_index()
atraso_medio_titulos_liquidados.columns = ['DOCUMENTO', 'FORNECEDOR', 'ATRASO_MEDIO_TITULOS_LIQUIDADOS']

atraso_medio_titulos_liquidados

            DOCUMENTO     FORNECEDOR  ATRASO_MEDIO_TITULOS_LIQUIDADOS
0      00000000910228  Casa do Adubo                      -165.000000
1      00000001339907  Casa do Adubo                        18.000000
2      00000001425650  Casa do Adubo                         0.000000
3      00000001606280  Casa do Adubo                       -75.000000
4      00000001607251  Casa do Adubo                       -30.000000
...               ...            ...                              ...
94991  97548211000103           Gama                         4.600000
94992  97550450000190           Gama                         5.187500
94993  97550658000109  Casa do Adubo                         0.000000
94994  97551402000116  Casa do Adubo                       -43.636364
94995  97552416000154  Casa do Adubo                       -15.824074

[94996 rows x 3 columns]

# Atraso Max liquidados;

In [47]:
atraso_max_titulos_liquidados = copy.copy(base)
#Pegando somente casos válidos para análise
atraso_max_titulos_liquidados = atraso_max_titulos_liquidados[pd.notna(atraso_max_titulos_liquidados['DT_PAGAMENTO'])]
# Criando aux para cálculo prazo médio
atraso_max_titulos_liquidados['DT_VENCIMENTO'] = pd.to_datetime(atraso_max_titulos_liquidados['DT_VENCIMENTO'])
atraso_max_titulos_liquidados['DT_PAGAMENTO'] = pd.to_datetime(atraso_max_titulos_liquidados['DT_PAGAMENTO'])

# Calculo Diferenças Dias (Pagamento - Vencimento)
atraso_max_titulos_liquidados['DIF_DIAS_PAGAMENTO'] = (atraso_max_titulos_liquidados['DT_PAGAMENTO'] - atraso_max_titulos_liquidados['DT_VENCIMENTO']).dt.days

atraso_max_titulos_liquidados = atraso_max_titulos_liquidados.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'DIF_DIAS_PAGAMENTO': 'max'
}).reset_index()
atraso_max_titulos_liquidados.columns = ['DOCUMENTO', 'FORNECEDOR', 'ATRASO_MAX_TITULOS_LIQUIDADOS']

atraso_max_titulos_liquidados

            DOCUMENTO     FORNECEDOR  ATRASO_MAX_TITULOS_LIQUIDADOS
0      00000000910228  Casa do Adubo                            -30
1      00000001339907  Casa do Adubo                             42
2      00000001425650  Casa do Adubo                              0
3      00000001606280  Casa do Adubo                            -30
4      00000001607251  Casa do Adubo                            -30
...               ...            ...                            ...
94991  97548211000103           Gama                             20
94992  97550450000190           Gama                             22
94993  97550658000109  Casa do Adubo                              0
94994  97551402000116  Casa do Adubo                              0
94995  97552416000154  Casa do Adubo                             64

[94996 rows x 3 columns]

# Atraso min liquidados;

In [48]:
atraso_min_titulos_liquidados = copy.copy(base)
#Pegando somente casos válidos para análise
atraso_min_titulos_liquidados = atraso_min_titulos_liquidados[pd.notna(atraso_min_titulos_liquidados['DT_PAGAMENTO'])]
# Criando aux para cálculo prazo médio
atraso_min_titulos_liquidados['DT_VENCIMENTO'] = pd.to_datetime(atraso_min_titulos_liquidados['DT_VENCIMENTO'])
atraso_min_titulos_liquidados['DT_PAGAMENTO'] = pd.to_datetime(atraso_min_titulos_liquidados['DT_PAGAMENTO'])

# Calculo Diferenças Dias (Pagamento - Vencimento)
atraso_min_titulos_liquidados['DIF_DIAS_PAGAMENTO'] = (atraso_min_titulos_liquidados['DT_PAGAMENTO'] - atraso_min_titulos_liquidados['DT_VENCIMENTO']).dt.days

atraso_min_titulos_liquidados = atraso_min_titulos_liquidados.groupby(['DOCUMENTO', 'FORNECEDOR']).agg({
'DIF_DIAS_PAGAMENTO': 'min'
}).reset_index()
atraso_min_titulos_liquidados.columns = ['DOCUMENTO', 'FORNECEDOR', 'ATRASO_MIN_TITULOS_LIQUIDADOS']

atraso_min_titulos_liquidados

            DOCUMENTO     FORNECEDOR  ATRASO_MIN_TITULOS_LIQUIDADOS
0      00000000910228  Casa do Adubo                           -300
1      00000001339907  Casa do Adubo                              1
2      00000001425650  Casa do Adubo                              0
3      00000001606280  Casa do Adubo                           -120
4      00000001607251  Casa do Adubo                            -30
...               ...            ...                            ...
94991  97548211000103           Gama                              0
94992  97550450000190           Gama                              0
94993  97550658000109  Casa do Adubo                              0
94994  97551402000116  Casa do Adubo                            -90
94995  97552416000154  Casa do Adubo                           -116

[94996 rows x 3 columns]

CRUZANDO P VER SE DEU TUDO BOM

In [49]:
validando = qtde_titulos_abertos_vencidos.merge(valor_titulos_abertos_vencidos, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(qtde_titulos_abertos_vincendo, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(valor_titulos_abertos_vincendo, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(prazo_medio_abertos_vencidos, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(prazo_medio_abertos_vincendos, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(qtde_titulos_liquidados, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(valor_titulos_liquidados, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(prazo_medio_titulos_liquidados, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(atraso_medio_titulos_liquidados, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(atraso_max_titulos_liquidados, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')
validando = validando.merge(atraso_min_titulos_liquidados, on=['DOCUMENTO', 'FORNECEDOR'], how='outer')

validando = validando[validando['DOCUMENTO'] == '73418758000118']

validando

,DOCUMENTO,FORNECEDOR,QTDE_TITULOS_ABERTOS_VENCIDOS,VALOR_TITULOS_ABERTOS_VENCIDOS,QTDE_TITULOS_ABERTOS_VINCENDO,VALOR_TITULOS_ABERTOS_VINCENDO,PRAZO_MEDIO_ABERTOS_VENCIDOS,PRAZO_MEDIO_ABERTOS_VINCENDOS,QTDE_TITULOS_LIQUIDADOS,VALOR_TITULOS_LIQUIDADOS,PRAZO_MEDIO_TITULOS_LIQUIDADOS,ATRASO_MEDIO_TITULOS_LIQUIDADOS,ATRASO_MAX_TITULOS_LIQUIDADOS,ATRASO_MIN_TITULOS_LIQUIDADOS
3787,73418758000118,Casa do Adubo,10.0,5249.33,35.0,9871.88,107.2,130.114286,464.0,162424.82,78.862069,-7.015086,34.0,-173.0